# Generated by Django 5.0.6 on 2026-09-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('imagen_frontal', models.TextField(blank=True, help_text='URL o ruta de la imagen frontal del pokémon', null=True)),
                ('imagen_posterior', models.TextField(blank=True, null=True)),
                ('imagen_shiny', models.TextField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tipos', models.CharField(blank=True, help_text='Ej: fire,flying (separados por coma)', max_length=100)),
            ],
            options={
                'verbose_name': 'Pokémon (local / SQLite)',
                'verbose_name_plural': 'Pokémon (local / SQLite)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AtaqueLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ataque', models.CharField(max_length=100)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques', to='pokedex.pokemonlocal')),
            ],
            options={
                'verbose_name': 'Ataque (local)',
                'verbose_name_plural': 'Ataques (local)',
            },
        ),
    ]
