# Generated by Django 5.0.6 on 2026-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ataque', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pokemon_ataques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('imagen_frontal', models.TextField(blank=True, null=True)),
                ('imagen_posterior', models.TextField(blank=True, null=True)),
                ('imagen_shiny', models.TextField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tipos', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'pokemon',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
